### ISSUE TITLE
Does this code still work for you?

### ISSUE THREAD

**Issue by CordThomas** [ehampshire/sunpower#2]
I have tried to implement this code.   Is the sunpower monitor (for the IP address in the config) the address of my supervisor?   What IP is this?   I am quite keen on this work and wonder based on the discussion on solarpaneltalk whether this is still possible.  I do believe that the traffic is now encrypted from the supervisor to the Sunpower AWS systems via TLS 1.2 but not positive.

**Comment by ehampshire** [comment]
I just tested it, and yes, it does still work.  As commented in the sp_monitor_json.conf file the IP is the IP of your supervisor.  If you are directly connected to it via the Ethernet cable you should be good to go with the example.  If you are not and using a Pi to bridge between the supervisor network (172.27.153.0/255.255.255.0) and your home network, you will need to add a route as detailed in the solarpaneltalk forum.

# SunPower PV monitor IP
ipAddress=172.27.153.1

**Comment by ehampshire** [comment]
I just committed some updated code (index2.php) that works with the direct-query method to the SP supervisor.  Check that out and see if it works for you.
