### ISSUE TITLE
Just got panels trying to get this going. 

### ISSUE THREAD

**Issue by jimprintsthings** [ehampshire/sunpower#3]
I'm not great with python, but i've gotten multiple projects going. This one keeps bombing out on me, thought I'd check to see if I'm missing something obvious.  Generally this is the error Im getting:

Attempting to hit URL: http://172.27.153.1/cgi-bin/dl_cgi?Command=DeviceList
Traceback (most recent call last):
  File "./sp_monitor_json2.py", line 318, in <module>
    sys.exit(main())
  File "./sp_monitor_json2.py", line 70, in main
    ac_power = float(x["p_3phsum_kw"])  * 1000
KeyError: 'p_3phsum_kw'

I've really kicked this a bunch, tried trapping it but so far I've failed :) 
Any insight would be appreciated .

**Comment by ehampshire** [comment]
Haven't look at this in a long time, new version committed that skips the entries giving you this error.
